<?php

$current_time = date("Y-m-d H:i:s");

echo <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>CGI PHP HTML Page</title>
</head>
<body>
	<h1>Hello from PHP CGI Script!</h1>
	<p>This is a simple HTML page generated by a PHP CGI script.</p>
	<h2>Environment Variables:</h2>
	<ul>
HTML;

foreach ($_SERVER as $key => $value) {
	echo "<li>$key = $value</li>";
}

echo <<<HTML
	</ul>
	<h2>Current Time:</h2>
	<p>$current_time</p>
</body>
</html>
HTML;
?>
