import os
from datetime import datetime

def main():
	current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

	html_content = """
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>CGI Python HTML Page</title>
	</head>
	<body>
		<h1>Hello from Python CGI Script</h1>
		<p>This is a simple HTML page generated by a Python CGI script</p>
		<h2>Environment Variables:</h2>
		<ul>
	"""
		
	for key, value in os.environ.items():
		html_content += f"<li>{key} = {value}</li>"
		
	html_content += f"""
		</ul>
		<h2>Current Time:</h2>
		<p>{current_time}</p>
	</body>
	</html>
	"""
		
	print(html_content)

if __name__ == "__main__":
	main()
